// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLPP22Jxu861Eq7S8KiXiCGbg_tkNwYA',
    appId: '1:928003373109:web:c1cac1cb1ce0514e42597c',
    messagingSenderId: '928003373109',
    projectId: 'stylee-97181',
    authDomain: 'stylee-97181.firebaseapp.com',
    storageBucket: 'stylee-97181.firebasestorage.app',
    measurementId: 'G-1VFW3DQYYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3g-1g5YXd6RovCwOnCv0bshqARalyXU0',
    appId: '1:928003373109:android:929065ab6fd3297142597c',
    messagingSenderId: '928003373109',
    projectId: 'stylee-97181',
    storageBucket: 'stylee-97181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB044hI6bgWrpJEfw0EYJ_Bfbt32VlBUBQ',
    appId: '1:928003373109:ios:d0369aa46844148142597c',
    messagingSenderId: '928003373109',
    projectId: 'stylee-97181',
    storageBucket: 'stylee-97181.firebasestorage.app',
    iosBundleId: 'com.example.styleeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB044hI6bgWrpJEfw0EYJ_Bfbt32VlBUBQ',
    appId: '1:928003373109:ios:d0369aa46844148142597c',
    messagingSenderId: '928003373109',
    projectId: 'stylee-97181',
    storageBucket: 'stylee-97181.firebasestorage.app',
    iosBundleId: 'com.example.styleeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoLPP22Jxu861Eq7S8KiXiCGbg_tkNwYA',
    appId: '1:928003373109:web:c750294aeb3cae8942597c',
    messagingSenderId: '928003373109',
    projectId: 'stylee-97181',
    authDomain: 'stylee-97181.firebaseapp.com',
    storageBucket: 'stylee-97181.firebasestorage.app',
    measurementId: 'G-BE1Y1Y6WY0',
  );

}